<a href="https://colab.research.google.com/github/ikabrain/UML501-IKANSH-MAHAJAN-102303754-LabAssignments/blob/main/ML_assign1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment - 1 (Based on NumPy)
---

In [1]:
import numpy as np

---
#### Q1. Questions on Basic NumPy Array

##### (a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [2]:
arr = np.array([1, 2, 3, 6, 4, 5])
print(f"Original array: {arr}")

arr = np.flip(arr)
print(f"Reversed array: {arr}")

Original array: [1 2 3 6 4 5]
Reversed array: [5 4 6 3 2 1]


##### (b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two NumPy in-built methods

In [3]:
# Using np.ndarray.flatten()
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print("Original array:-")
print(array1)

array1 = array1.flatten()
print(f"Flattened array: {array1}")

Original array:-
[[1 2 3]
 [2 4 5]
 [1 2 3]]
Flattened array: [1 2 3 2 4 5 1 2 3]


In [4]:
# Using np.ndarray.reshape(-1) =>  When -1 is used as one of the dimensions in reshape, NumPy automatically calculates the appropriate size for that dimension
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print("Original array:-")
print(array1)

array1 = array1.reshape(-1)
print(f"Reshaped array: {array1}")

Original array:-
[[1 2 3]
 [2 4 5]
 [1 2 3]]
Reshaped array: [1 2 3 2 4 5 1 2 3]


##### (c) Compare the following numpy arrays:

`arr1 = np.array([[1, 2], [3, 4]])`

`arr2 = np.array([[1, 2], [3, 4]])`

In [5]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

print(f"Are both arrays same:-")
print((arr1 == arr2).all())
print(np.array_equal(arr1, arr2))

Are both arrays same:-
True
True


##### (d) Find the most frequent value and their indice(s) in the following arrays:
i. `x = np.array([1,2,3,4,5,1,2,1,1,1])`

ii. `y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])`

In [6]:
def calculate_mode(arr: np.ndarray):
  unique_vals, counts = np.unique(arr, return_counts=True)
  mode_indices = np.where(counts == counts.max())
  return unique_vals[mode_indices].tolist()

In [7]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
print(f"x = {x}")
print(f"Mode(s) of x = {calculate_mode(x)}")

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
print(f"y = {y}")
print(f"Mode(s) of y = {calculate_mode(y)}")

x = [1 2 3 4 5 1 2 1 1 1]
Mode(s) of x = [1]
y = [1 1 1 2 3 4 2 4 3 3]
Mode(s) of y = [1, 3]


##### (e) For the array `gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')`
Find

i. Sum of all elements

ii. Sum of all elements row-wise

iii. Sum of all elements column-wise

In [8]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

print("Matrix:-")
print(gfg, end="\n\n")

# i. Sum of all elements
s = gfg.sum()
print(f"Sum of all elements = {s}\n")

# ii. Row-wise sum
s1 = gfg.sum(axis=1).flatten().tolist()[0]
for i, row in enumerate(s1, start=1):
    print(f"Sum of row {i} = {row}")

print()

# iii. Col-wise sum
s2 = gfg.sum(axis=0).flatten().tolist()[0]
for j, col in enumerate(s2, start=1):
    print(f"Sum of column {j} = {col}")

Matrix:-
[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]

Sum of all elements = 45

Sum of row 1 = 14
Sum of row 2 = 16
Sum of row 3 = 15

Sum of column 1 = 20
Sum of column 2 = 9
Sum of column 3 = 16


##### (f) For the matrix: `n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])`, find

i. Sum of diagonal elements

ii. Eigen values of matrix

iii. Eigen vectors of matrix

iv. Inverse of matrix

v. Determinant of matrix

In [9]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
print(f"Array:-\n{n_array}\n")

# i. Sum of diagonal elements
diag = np.trace(n_array)
print(f"Sum of main diagonal elements = {diag}\n")

# ii. Eigenvalues of matrix A => Solutions of det(A - xI) = 0
# iii. Eigenvectors of mtrx A => Solutions of Ax = lx
evals, evects = np.linalg.eig(n_array)
print(f"Eigenvalues = {', '.join(np.round(evals, decimals=4).astype(str))}")
print(f"Eigenvectors:-")
for i in evects:
    print("[", end="")
    for j in i:
        print(j.round(decimals=4), end=", ") if (j != i[-1]) else print(j.round(decimals=4), end="]\n")
print()

# iv. Inverse of matrix = adj(A) / det(A)
n_inv = np.linalg.inv(n_array)
print(f"Inverse:-\n{n_inv.round(decimals=4)}\n")

# v. Determinant of matrix
n_det = np.linalg.det(n_array)
print(f"Determinant = {n_det:.4f}")

Array:-
[[55 25 15]
 [30 44  2]
 [11 45 77]]

Sum of main diagonal elements = 176

Eigenvalues = 98.1684, 28.097, 49.7346
Eigenvectors:-
[0.4575, 0.3464, -0.1502]
[0.2845, -0.7278, -0.4852]
[0.8425, 0.5918, 0.8614]

Inverse:-
[[ 0.024  -0.0091 -0.0044]
 [-0.0167  0.0297  0.0025]
 [ 0.0063 -0.016   0.0122]]

Determinant = 137180.0000


##### (g) Multiply the following matrices and also find covariance between matrices using NumPy:

###### i.
```
p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]
```

In [13]:
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])
print(f"p = \n{p}\n")
print(f"q = \n{q}\n")

# Matrix mult
prod = p @ q
print(f"Matrix product p × q = \n{prod}\n")

# Covariance
cov = np.cov(p, q)
print(f"Covariance between rows of p & q = \n{cov}")

p = 
[[1 2]
 [2 3]]

q = 
[[4 5]
 [6 7]]

Matrix product p × q = 
[[16 19]
 [26 31]]

Covariance between rows of p & q = 
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


###### ii.
```
p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]
```

In [16]:
p = np.array([[1, 2], [2, 3], [4, 5]])
q = np.array([[4, 5, 1], [6, 7, 2]])
print(f"p = \n{p}\n")
print(f"q = \n{q}\n")

# Matrix mult
prod = p @ q
print(f"Matrix product p × q = \n{prod}\n")

# Covariance
cov = np.cov(p, q.T)
print(f"Covariance between rows of p & q = \n{cov}")

p = 
[[1 2]
 [2 3]
 [4 5]]

q = 
[[4 5 1]
 [6 7 2]]

Matrix product p × q = 
[[16 19  5]
 [26 31  8]
 [46 55 14]]

Covariance between rows of p & q = 
[[0.5 0.5 0.5 1.  1.  0.5]
 [0.5 0.5 0.5 1.  1.  0.5]
 [0.5 0.5 0.5 1.  1.  0.5]
 [1.  1.  1.  2.  2.  1. ]
 [1.  1.  1.  2.  2.  1. ]
 [0.5 0.5 0.5 1.  1.  0.5]]


##### (h) For the matrices: `x = np.array([[2, 3, 4], [3, 2, 9]])` ; `y = np.array([[1, 5, 0], [5, 10, 3]])`, find inner, outer and cartesian product?

In [34]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print(f"x = \n{x}\n")
print(f"y = \n{y}\n")

# Inner/Row-wise Dot product <A, B> = ∑(from i=1 to m)∑(from j=1 to n)(Aᵢⱼ * Bᵢⱼ) = trace(AᵀB)
inner_prod = np.inner(x, y)
print(f"<x, y> = \n{inner_prod}\n")

# Outer/Cross product A ⊗ B = taking each element of A, multiplying it by entire B, then stacking them together = trace(ABᵀ)
outer_prod = np.outer(x, y)
print(f"x ⊗ y = \n{outer_prod}\n")

# Cartesian product = all pairwise combinations of elements from x and y
from itertools import product
cartes_prod = np.array(list(product(x.flatten(), y.flatten())))
print(f"Cartesian product of {{x, y}} = \n{cartes_prod}\n")

x = 
[[2 3 4]
 [3 2 9]]

y = 
[[ 1  5  0]
 [ 5 10  3]]

<x, y> = 
[[17 52]
 [13 62]]

x ⊗ y = 
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]

Cartesian product of {x, y} = 
[[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]



---
#### Q2. Based on NumPy Mathematics and Statistics

##### (a) For the array: `array = np.array([[1, -2, 3],[-4, 5, -6]])`


In [35]:
array = np.array([[1, -2, 3], [-4, 5, -6]])

###### (i) Find element-wise absolute value


In [62]:
np.abs(array)

array([[1, 2, 3],
       [4, 5, 6]])

###### (ii) Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each row.

In [88]:
percentiles = np.array([25, 50, 75])

# For flattened array
qtile1 = np.quantile(array.flatten(), percentiles/100)
for i in range(len(percentiles)):
    print(f"{percentiles[i]}th percentile of entire matrix = {qtile1[i]:8.2f}")
print()

# For each column, axis=0
qtile2 = np.quantile(array, percentiles/100, axis=0)
for i in range(len(percentiles)):
    for j in range(array.shape[1]):
        print(f"{percentiles[i]}th percentile of col {j+1} = {qtile2[i][j]:8.2f}")
print()

# For each row, axis=1
qtile3 = np.quantile(array, percentiles/100, axis=1)
for i in range(len(percentiles)):
    for j in range(array.shape[0]):
        print(f"{percentiles[i]}th percentile of row {j+1} = {qtile3[i][j]:5.2f}")
print()

25th percentile of entire matrix =    -3.50
50th percentile of entire matrix =    -0.50
75th percentile of entire matrix =     2.50

25th percentile of col 1 =    -2.75
25th percentile of col 2 =    -0.25
25th percentile of col 3 =    -3.75
50th percentile of col 1 =    -1.50
50th percentile of col 2 =     1.50
50th percentile of col 3 =    -1.50
75th percentile of col 1 =    -0.25
75th percentile of col 2 =     3.25
75th percentile of col 3 =     0.75

25th percentile of row 1 = -0.50
25th percentile of row 2 = -5.00
50th percentile of row 1 =  1.00
50th percentile of row 2 = -4.00
75th percentile of row 1 =  2.00
75th percentile of row 2 =  0.50



###### (iii) Mean, Median and Standard Deviation of flattened array, of each column, and each row

In [111]:
# For flatenned array
mean1 = array.flatten().mean()
med1 = np.median(array.flatten())
sd1 = array.flatten().std()
print(f"Mean of entire matrix = {mean1:20.2f}")
print(f"Median of entire matrix = {med1:18.2f}")
print(f"Standard Deviation of entire matrix = {sd1:6.2f}\n")
print("-"*100)

# For each column, axis=0
mean2 = array.mean(axis=0)
med2 = np.median(array, axis=0)
sd2 = array.std(axis=0)
for i in range(array.shape[1]):
    print(f"Mean of col {i} = {mean2[i]:20.2f}")
    print(f"Median of col {i} = {med2[i]:18.2f}")
    print(f"Standard Deviation of col {i} = {sd2[i]:6.2f}")
    print()
print("-"*100)

# For each row, axis=1
mean3 = array.mean(axis=1)
med3 = np.median(array, axis=1)
sd3 = array.std(axis=1)
for i in range(array.shape[0]):
    print(f"Mean of row {i} = {mean3[i]:23.2f}")
    print(f"Median of row {i} = {med3[i]:21.2f}")
    print(f"Standard Deviation of row {i} = {sd3[i]:9.2f}")
    print()
print("-"*100)

Mean of entire matrix =                -0.50
Median of entire matrix =              -0.50
Standard Deviation of entire matrix =   3.86

----------------------------------------------------------------------------------------------------
Mean of col 0 =                -1.50
Median of col 0 =              -1.50
Standard Deviation of col 0 =   2.50

Mean of col 1 =                 1.50
Median of col 1 =               1.50
Standard Deviation of col 1 =   3.50

Mean of col 2 =                -1.50
Median of col 2 =              -1.50
Standard Deviation of col 2 =   4.50

----------------------------------------------------------------------------------------------------
Mean of row 0 =                    0.67
Median of row 0 =                  1.00
Standard Deviation of row 0 =      2.05

Mean of row 1 =                   -1.67
Median of row 1 =                 -4.00
Standard Deviation of row 1 =      4.78

------------------------------------------------------------------------------------

##### (b) For the array: `a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])`. Find floor, ceiling and truncated value, rounded values.

In [113]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
print(f"Original array: \n{a.tolist()}\n")

# Floor: Largest integer less than or equal to the value
floor_vals = np.floor(a)
print(f"Floor values: \n{floor_vals.tolist()}\n")

# Ceiling: Smallest integer greater than or equal to the value
ceil_vals = np.ceil(a)
print(f"Ceiling values: \n{ceil_vals.tolist()}\n")

# Truncated: Remove fractional part towards zero (same as int() in Python)
trunc_vals = np.trunc(a)
print(f"Truncated values: \n{trunc_vals.tolist()}\n")

# Rounded: Rounds to nearest integer, half to even (banker’s rounding)
round_vals = np.round(a)
print(f"Rounded values: \n{round_vals.tolist()}\n")

Original array: 
[-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0]

Floor values: 
[-2.0, -2.0, -1.0, 0.0, 1.0, 1.0, 3.0]

Ceiling values: 
[-1.0, -1.0, -0.0, 1.0, 2.0, 2.0, 3.0]

Truncated values: 
[-1.0, -1.0, -0.0, 0.0, 1.0, 1.0, 3.0]

Rounded values: 
[-2.0, -2.0, -0.0, 0.0, 2.0, 2.0, 3.0]



---
#### Q3: Based on Searching and Sorting