<a href="https://colab.research.google.com/github/ikabrain/UML501-IKANSH-MAHAJAN-102303754-LabAssignments/blob/main/ML_assign1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment - 1 (Based on NumPy)
---

In [ ]:
import numpy as np

#### Q1. Questions on Basic NumPy Array

##### (a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [ ]:
arr = np.array([1, 2, 3, 6, 4, 5])
print(f"Original array: {arr}")

arr = np.flip(arr)
print(f"Reversed array: {arr}")

Original array: [1 2 3 6 4 5]
Reversed array: [5 4 6 3 2 1]


##### (b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two NumPy in-built methods

In [ ]:
# Using np.ndarray.flatten()
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print("Original array:-")
print(array1)

array1 = array1.flatten()
print(f"Flattened array: {array1}")

Original array:-
[[1 2 3]
 [2 4 5]
 [1 2 3]]
Flattened array: [1 2 3 2 4 5 1 2 3]


In [ ]:
# Using np.ndarray.reshape(-1) =>  When -1 is used as one of the dimensions in reshape, NumPy automatically calculates the appropriate size for that dimension
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print("Original array:-")
print(array1)

array1 = array1.reshape(-1)
print(f"Reshaped array: {array1}")

Original array:-
[[1 2 3]
 [2 4 5]
 [1 2 3]]
Reshaped array: [1 2 3 2 4 5 1 2 3]


##### (c) Compare the following numpy arrays:

`arr1 = np.array([[1, 2], [3, 4]])`

`arr2 = np.array([[1, 2], [3, 4]])`

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

print(f"Are both arrays same:-")
print((arr1 == arr2).all())
print(np.array_equal(arr1, arr2))

Are both arrays same:-
True
True


##### (d) Find the most frequent value and their indice(s) in the following arrays:
i. `x = np.array([1,2,3,4,5,1,2,1,1,1])`

ii. `y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])`

In [ ]:
def calculate_mode(arr: np.ndarray):
  unique_vals, counts = np.unique(arr, return_counts=True)
  mode_indices = np.where(counts == counts.max())
  return unique_vals[mode_indices].tolist()

In [26]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
print(f"x = {x}")
print(f"Mode(s) of x = {calculate_mode(x)}")

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
print(f"y = {y}")
print(f"Mode(s) of y = {calculate_mode(y)}")

x = [1 2 3 4 5 1 2 1 1 1]
Mode(s) of x = [1]
y = [1 1 1 2 3 4 2 4 3 3]
Mode(s) of y = [1, 3]


##### (e) For the array `gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')`
Find

i. Sum of all elements

ii. Sum of all elements row-wise

iii. Sum of all elements column-wise

In [74]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

print("Matrix:-")
print(gfg, end="\n\n")

# i. Sum of all elements
s = gfg.sum()
print(f"Sum of all elements = {s}\n")

# ii. Row-wise sum
s1 = gfg.sum(axis=1).flatten().tolist()[0]
for i, row in enumerate(s1, start=1):
    print(f"Sum of row {i} = {row}")

print()

# iii. Col-wise sum
s2 = gfg.sum(axis=0).flatten().tolist()[0]
for j, col in enumerate(s2, start=1):
    print(f"Sum of column {j} = {col}")

Matrix:-
[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]

Sum of all elements = 45

Sum of row 1 = 14
Sum of row 2 = 16
Sum of row 3 = 15

Sum of column 1 = 20
Sum of column 2 = 9
Sum of column 3 = 16


##### (f) For the matrix: `n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])`, find

i. Sum of diagonal elements

ii. Eigen values of matrix

iii. Eigen vectors of matrix

iv. Inverse of matrix

v. Determinant of matrix

In [115]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
print(f"Array:-\n{n_array}\n")

# i. Sum of diagonal elements
diag = np.trace(n_array)
print(f"Sum of main diagonal elements = {diag}\n")

# ii. Eigenvalues of matrix A => Solutions of det(A - xI) = 0
# iii. Eigenvectors of mtrx A => Solutions of Ax = lx
evals, evects = np.linalg.eig(n_array)
print(f"Eigenvalues = {', '.join(np.round(evals, decimals=4).astype(str))}")
print(f"Eigenvectors:-")
for i in evects:
    print("[", end="")
    for j in i:
        print(j.round(decimals=4), end=", ") if (j != i[-1]) else print(j.round(decimals=4), end="]\n")
print()

# iv. Inverse of matrix = adj(A) / det(A)
n_inv = np.linalg.inv(n_array)
print(f"Inverse:-\n{n_inv.round(decimals=4)}\n")

# v. Determinant of matrix
n_det = np.linalg.det(n_array)
print(f"Determinant = {n_det:.4f}")

Array:-
[[55 25 15]
 [30 44  2]
 [11 45 77]]

Sum of main diagonal elements = 176

Eigenvalues = 98.1684, 28.097, 49.7346
Eigenvectors:-
[0.4575, 0.3464, -0.1502]
[0.2845, -0.7278, -0.4852]
[0.8425, 0.5918, 0.8614]

Inverse:-
[[ 0.024  -0.0091 -0.0044]
 [-0.0167  0.0297  0.0025]
 [ 0.0063 -0.016   0.0122]]

Determinant = 137180.0000


##### (g) Multiply the following matrices and also find covariance between matrices using NumPy:

###### i.
```
p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]
```

In [126]:
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])
print(f"p = \n{p}\n")
print(f"q = \n{q}\n")

# Matrix mult
prod = p @ q
print(f"Matrix product of p × q = \n{prod}")

# Covariance
np.cov(p)
np.cov(q)

p = 
[[1 2]
 [2 3]]

q = 
[[4 5]
 [6 7]]

Matrix product of p × q = 
[[16 19]
 [26 31]]


array([[0.5, 0.5],
       [0.5, 0.5]])