<a href="https://colab.research.google.com/github/ikabrain/UML501-IKANSH-MAHAJAN-102303754-LabAssignments/blob/main/ML_assign1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment - 1 (Based on NumPy)
---

In [ ]:
import numpy as np

#### Q1. Questions on Basic NumPy Array

##### (a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [ ]:
arr = np.array([1, 2, 3, 6, 4, 5])
print(f"Original array: {arr}")

arr = np.flip(arr)
print(f"Reversed array: {arr}")

Original array: [1 2 3 6 4 5]
Reversed array: [5 4 6 3 2 1]


##### (b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two NumPy in-built methods

In [ ]:
# Using np.ndarray.flatten()
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print("Original array:-")
print(array1)

array1 = array1.flatten()
print(f"Flattened array: {array1}")

Original array:-
[[1 2 3]
 [2 4 5]
 [1 2 3]]
Flattened array: [1 2 3 2 4 5 1 2 3]


In [ ]:
# Using np.ndarray.reshape(-1) =>  When -1 is used as one of the dimensions in reshape, NumPy automatically calculates the appropriate size for that dimension
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print("Original array:-")
print(array1)

array1 = array1.reshape(-1)
print(f"Reshaped array: {array1}")

Original array:-
[[1 2 3]
 [2 4 5]
 [1 2 3]]
Reshaped array: [1 2 3 2 4 5 1 2 3]


##### (c) Compare the following numpy arrays:

`arr1 = np.array([[1, 2], [3, 4]])`

`arr2 = np.array([[1, 2], [3, 4]])`

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

print(f"Are both arrays same:-")
print((arr1 == arr2).all())
print(np.array_equal(arr1, arr2))

Are both arrays same:-
True
True


##### (d) Find the most frequent value and their indice(s) in the following arrays:
i. `x = np.array([1,2,3,4,5,1,2,1,1,1])`

ii. `y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])`

In [ ]:
def calculate_mode(arr: np.ndarray):
  unique_vals, counts = np.unique(arr, return_counts=True)
  mode_indices = np.where(counts == counts.max())
  return unique_vals[mode_indices].tolist()

In [ ]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
print(f"x = {x}")
print(f"Mode(s) of x = {''.join(calculate_mode(x))}")

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
print(f"y = {y}")
print(f"Mode(s) of y = {''.join(calculate_mode(y))}")

x = [1 2 3 4 5 1 2 1 1 1]
Mode(s) of x = [ 1 ]
y = [1 1 1 2 3 4 2 4 3 3]
Mode(s) of y = [ 1 ,   3 ]
